# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:

    jsonapi.category.hydrator:
        class: JsonBundle\Category\Hydrator
        arguments: ['@doctrine.orm.default_entity_manager']
