#json:
#    resource: "@JsonBundle/Resources/config/routing.yml"
#    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: '@AppBundle/Controller/Api'
    type: annotation

#article_list:
#    path:      /api/articles
#    defaults:  { _controller: AppBundle:Article:getArticles }

