<<<<<<< HEAD
#json:
#    resource: "@JsonBundle/Resources/config/routing.yml"
#    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

api:
    resource: '@AppBundle/Controller/Api'
    type: annotation

#article_list:
#    path:      /api/articles
#    defaults:  { _controller: AppBundle:Article:getArticles }
=======
article_list:
    path:      /articles
    defaults:  { _controller: AppBundle:Article:getArticles }
>>>>>>> fcbf5250b15b4d67a79fee76fec9b334d17727d3

