# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
imports:
    - { resource: json-api/category_services.yml}

parameters:
    #parameter_name: value

services:

    jsonapi.base.service:
        class: JsonBundle\Services\BaseJSONApiBundle
        arguments: ['@doctrine.orm.default_entity_manager']

    jsonapi.hydrator.service:
        class: JsonBundle\Services\BaseHydrator
        arguments: ['@doctrine.orm.default_entity_manager']

    jsonapi.validator:
        class: JsonBundle\Services\Validator\Validator
        arguments: ['@validator']

    jsonapi.request:
        class: JsonBundle\Request\JSONApiRequest
        arguments: ['@request_stack']

#    jsonapi.request.listener:
#        class: JsonBundle\Listeners\RequestListener
#        arguments: ['@service_container']
#        tags:
#            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    jsonapi.listener:
        class: JsonBundle\Listeners\ControllerListener
        arguments: ['@service_container']
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }
