# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    jsonapi.base.service:
        class: JsonBundle\Services\BaseJSONApiBundle
        arguments: ['@doctrine.orm.default_entity_manager']

    jsonapi.hydrator.service:
        class: JsonBundle\Services\BaseHydrator
        arguments: ['@doctrine.orm.default_entity_manager']

    jsonapi.validator:
        class: JsonBundle\Services\Validator\Validator
        arguments: ['@validator', '@doctrine.orm.default_entity_manager']
